### ISSUE TITLE
Add option to store fragments to disk

### ISSUE THREAD

**Issue by FlowingSPDG** [FlowingSPDG/gotv-plus-go#22]
Currenrly all fragment will be saved in-memory.
But it costs too much RAMs if we have many matches/fragments.
Add option to save/load them to/from disk to avoid OOM.

**Comment by suom1** [comment]
An addition to this feature could be that you would be able to store how many games you would want to store in memory and on disk. And the application would then wipe old matches from memory and/or disk when the limit is reached!

**Comment by FlowingSPDG** [comment]
#32
