### ISSUE TITLE
[Question] Can you use this to avoid using CS:GO client?

### ISSUE THREAD

**Issue by kubo6472** [FlowingSPDG/gotv-plus-go#26]
I read through both the readme and the valve developer wiki article and I am still not sure if I understand. I assumed this can be used to transform GOTV data into a video stream, without the CS:GO client. Basically enabling headless streaming of such content. But the playcast command that is always referenced suggest, that it is rather supposed to be viewed inside CS:GO client.

**Comment by FlowingSPDG** [comment]
The answer is "no".
GOTV+ is like fragment of CSGO's "dem" file which is used to replay game match.
If you want to stream CSGO match to twitch.tv and youtube etc, you may need real CSGO client.
btw you can automate streaming and command execution by using HLAE's mirv_pgl command.
